### ISSUE TITLE
Found some issues using -s and --text some strings can't be found or doesn't work

### ISSUE THREAD

**Issue by bawzz234** [restyler/proxy-checker-cli#3]
Hello,

Thanks for adding socks4 support. The scripts works accurately on each protocol. Excellent work. 

While testing, I found 2 issues, using these commands/functions:

1. -s function is not working. After testing with -s, it gives an error and doesn't check or save the working proxies. 

Here is the error:

`(node:27800) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stop' of u
ndefined
    at Promise.all.then (C:\Users\Administrator\AppData\Roaming\npm\node_modules\proxy-che
cker-cli\bin\proxy-checker-cli:212:8)
(node:27800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error ori
ginated either by throwing inside of an async function without a catch block, or by reject
ing a promise which was not handled with .catch(). (rejection id: 1)
(node:27800) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In
 the future, promise rejections that are not handled will terminate the Node.js process wi
th a non-zero exit code.`

2. --text works on some strings and doesn't work on others. For example I used this url: https://raw.githubusercontent.com/imakewebthings/waypoints/master/licenses.txt and used string --text The MIT License but it didn't work. Gave 0 results.

I appreciate your work regarding this, thanks in advance.

Best Regards

**Comment by restyler** [comment]
Thank you for your bugreport! The -s fix is easy, and I've just pushed new version with the fix to npm. 
The github issue is trickier, related to underlying proxy agent. https://github.com/zjael/simple-proxy-agent/issues/24 I couldn't quickly fix it but I may try to do another try in a few days..

**Comment by bawzz234** [comment]
Hello, 

Just tried the latest version. I think the problem is still there with the -s function. Now it doesn't give any error but it closes itself and doesn't check and save the proxies. Also, can you show the progress bar when -s is on. It will help knowing the status of checking. 

- [ ] Can you also add another function to disable table after checking (-table off and on) It will be very useful when checked big proxy lists. It takes a lot of time to show the table and it uses a lot of resources.  The table function is useful for small amount of proxies so having an option to turn it off or on would be great. If this function is added i think -s function won't be necessary. 

Best Regards
